//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace CDA.CDA {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CDABinding", Namespace="http://xmlns.oracle.com/orawsv/WS_RO/CDA")]
    public partial class CDAService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback XMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback HTMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback ASMXOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CDAService() {
            this.Url = global::CDA.Properties.Settings.Default.CDA_CDA_CDAService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event XMLCompletedEventHandler XMLCompleted;
        
        /// <remarks/>
        public event HTMLCompletedEventHandler HTMLCompleted;
        
        /// <remarks/>
        public event ASMXCompletedEventHandler ASMXCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("XML", RequestElementName="XMLInput", RequestNamespace="http://xmlns.oracle.com/orawsv/WS_RO/CDA", ResponseElementName="XMLOutput", ResponseNamespace="http://xmlns.oracle.com/orawsv/WS_RO/CDA", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void XML([System.Xml.Serialization.XmlElementAttribute("P_NADMI-NUMBER-IN")] double P_NADMINUMBERIN, [System.Xml.Serialization.XmlElementAttribute("P_NADMI-NUMBER-IN")] [System.Xml.Serialization.XmlIgnoreAttribute()] bool P_NADMINUMBERINSpecified) {
            this.Invoke("XML", new object[] {
                        P_NADMINUMBERIN,
                        P_NADMINUMBERINSpecified});
        }
        
        /// <remarks/>
        public void XMLAsync(double P_NADMINUMBERIN, bool P_NADMINUMBERINSpecified) {
            this.XMLAsync(P_NADMINUMBERIN, P_NADMINUMBERINSpecified, null);
        }
        
        /// <remarks/>
        public void XMLAsync(double P_NADMINUMBERIN, bool P_NADMINUMBERINSpecified, object userState) {
            if ((this.XMLOperationCompleted == null)) {
                this.XMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXMLOperationCompleted);
            }
            this.InvokeAsync("XML", new object[] {
                        P_NADMINUMBERIN,
                        P_NADMINUMBERINSpecified}, this.XMLOperationCompleted, userState);
        }
        
        private void OnXMLOperationCompleted(object arg) {
            if ((this.XMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XMLCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HTML", RequestElementName="S-HTMLInput", RequestNamespace="http://xmlns.oracle.com/orawsv/WS_RO/CDA", ResponseElementName="HTMLOutput", ResponseNamespace="http://xmlns.oracle.com/orawsv/WS_RO/CDA", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void HTML(System.Xml.XmlElement RETURN) {
            this.Invoke("HTML", new object[] {
                        RETURN});
        }
        
        /// <remarks/>
        public void HTMLAsync(System.Xml.XmlElement RETURN) {
            this.HTMLAsync(RETURN, null);
        }
        
        /// <remarks/>
        public void HTMLAsync(System.Xml.XmlElement RETURN, object userState) {
            if ((this.HTMLOperationCompleted == null)) {
                this.HTMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHTMLOperationCompleted);
            }
            this.InvokeAsync("HTML", new object[] {
                        RETURN}, this.HTMLOperationCompleted, userState);
        }
        
        private void OnHTMLOperationCompleted(object arg) {
            if ((this.HTMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HTMLCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ASMX", RequestElementName="ASMXInput", RequestNamespace="http://xmlns.oracle.com/orawsv/WS_RO/CDA", ResponseElementName="ASMXOutput", ResponseNamespace="http://xmlns.oracle.com/orawsv/WS_RO/CDA", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("P_CDA_DOCUMENT")]
        public System.Xml.XmlElement ASMX([System.Xml.Serialization.XmlElementAttribute("P_NADMI-NUMBER-IN")] double P_NADMINUMBERIN, [System.Xml.Serialization.XmlElementAttribute("P_CDA_DOCUMENT-XMLTYPE-OUT")] ASMXInputP_CDA_DOCUMENTXMLTYPEOUT P_CDA_DOCUMENTXMLTYPEOUT) {
            object[] results = this.Invoke("ASMX", new object[] {
                        P_NADMINUMBERIN,
                        P_CDA_DOCUMENTXMLTYPEOUT});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void ASMXAsync(double P_NADMINUMBERIN, ASMXInputP_CDA_DOCUMENTXMLTYPEOUT P_CDA_DOCUMENTXMLTYPEOUT) {
            this.ASMXAsync(P_NADMINUMBERIN, P_CDA_DOCUMENTXMLTYPEOUT, null);
        }
        
        /// <remarks/>
        public void ASMXAsync(double P_NADMINUMBERIN, ASMXInputP_CDA_DOCUMENTXMLTYPEOUT P_CDA_DOCUMENTXMLTYPEOUT, object userState) {
            if ((this.ASMXOperationCompleted == null)) {
                this.ASMXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnASMXOperationCompleted);
            }
            this.InvokeAsync("ASMX", new object[] {
                        P_NADMINUMBERIN,
                        P_CDA_DOCUMENTXMLTYPEOUT}, this.ASMXOperationCompleted, userState);
        }
        
        private void OnASMXOperationCompleted(object arg) {
            if ((this.ASMXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ASMXCompleted(this, new ASMXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ASMXInputP_CDA_DOCUMENTXMLTYPEOUT {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void XMLCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void HTMLCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void ASMXCompletedEventHandler(object sender, ASMXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ASMXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ASMXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591